sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'

branches:
  only:
  - master

before_install:
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - node --version
  - SERVICE=$SERVICE make ensure-dependencies
  - sleep 3
  - docker ps

script:
  - echo $SERVICE_ENV
  - make qa

matrix:
  include:
    - env: SERVICE=recipes-api
      services:
        - docker
    - env: SERVICE=recipes-crawler
      services:
        - docker