sudo: false

cache: yarn

language: node_js

env:
  global:
  - NODE_ENV='test'
  # DOCKER_USERNAME
  - secure: Tb8ubPmpPgFAOE0G7NqENpXvn9spfoM0fKTijJ8HWQ59hekzns9C2abnPt9lhC0+l8HApy739yAx6cneNR0XetJhdo7wE2d+OKLZ+H4otHwiZQIIGJXEYYTwuhwRNMTKAZu2S1lzrQUheWOLdfX/52aWcE1CtQkdSJger2wf2dZVC+lv+EdWp8TXjerGpEFt9S+knhyl8HgbObwFF15IzMcqzg9cH6A8nLpv7fiUAWVhUn5LUgSkqSbvysBgr+Xi8qvg3vm9BdSiFyIRNYfgNiE9ikZsL/qWHxuGk36AGDNjwHYZ1eEhPhBmVGnV3M0IeQdZXoNqDOI5ni5hVsszZiG+uMkHt5GXxG8GVIoJn/eCYONKNTDzDWzBX8LNxO5TpTUJqSrwPMv7L9rb2taVQKlxLr5uO7wLhuLZqJPstPBnbH+pXqmOaK/5f9wYFaL+Cg7oARAJOZvBpBYy8lYPij9upTD7wcf57KHrSXlo24UVJH5oAf8cozhgRSkE/Y9Vnu5kYbk2rUh4Cve7oOVsd1u/tpMIrqklfY4I854XonrtFl9f+UEwxugYoUa1kiTQ9seD4ZuYYPntZU/ESaSI//ozGDEhH8eZfakjgGiAiCoOe7xZCyGNVrttJWo8bnI60NDTOaG4QxFNVwnE9vBnXweBbm4DWy4/pFzjcyOP4tE=
  # DOCKER_PASSWORD
  - secure: YRj5wGJlwi4AjsT82a+2eoKgeHZaGGPePFX2oTj7ulK50yylBMmKYqNveAYMxjaZ63ketWQsG2qE3ZMG/wJ30AruC9cS6WFb5fv5apaLP9TOnwhZF8duzZkjUU/VPRa0f5hqC4kUZJQQNQe+zwyQQXT0CJPKsxFFcjiqGrrvCTddVTBEY13/COXbJDtgrANUbr7G632LEoD4kICnDzs6D1d9dtp6cYWg0IyiGV8iKT2uMICpbvIGpYXuOx6FqaJ3XUBRWs8Utzj6/D+6VtvEHOzhTYghEwubB/Sw8WrLgjZ3czSgqussFlODiogrHV9r/Ogb9mmYle+jptBqcpsuHrCbVb0zdL323UUpuUWb5Vz66L1AL8OwifgtfoTtFZNMkZTJQw69NAUGSbpxj1ycG6YtayEpriZk7ObPOBzQUxEul7+FydVVSIe54tY7/1NEh7TdUj9L+OqBBrcMzc8kxa9H1D0+Smzgj0ff+mlacPM9xFWc2nCVvu7s8lS5sB5J8Nwsaemzxhrsc6HYtwuLEYmtqUuAjiwqgf3ouo0oxYyk7xq+CdnSbdYrLCpxgkVzZIPNf4MITy5VNFrMMWqSgABnlmY+BLycpHm2xEZIk9yB4AgeBBxtSzqwW8QTnYo3hKORZxBJsTGYVFr8W/ELucR6BZx8sv5b6YsH3G5kM44=

branches:
  only:
  - master

before_install:
  - cd ./$SERVICE
  - nvm install
  - nvm use
  - node --version
  - SERVICE=$SERVICE make ensure-dependencies
  - sleep 3
  - docker ps

script:
  - make qa
  - TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make brand
  - DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD SERVICE=$SERVICE TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER make build

matrix:
  include:
    - env: SERVICE=recipes-api
      services:
        - docker
    - env: SERVICE=recipes-crawler
      services:
        - docker